### ISSUE TITLE
转码无效

### ISSUE THREAD

**Issue by running8Man** [typefo/mod_g729#1]
首先特别感谢您能贡献代码。按照安装步骤，我已经成功安装mod_g729模块，freeswitch显示加载成功。
客户端A和客户端B同时使用G729编码，可以顺利呼叫，如果A为G729 B为PCMA时 则呼叫后很快会挂断，请问这是什么原因呢？确认var.xml中已经添加G729支持

**Comment by typefo** [comment]
我使用转码是没有问题的，可能的原因是跟你的 freeswitch 编码协商列表和协商方式配置有关。
